### ISSUE TITLE
Support for accounts with more than 100 millions

### ISSUE THREAD

**Issue by crorodriguezro** [actualbudget/actual-server#100]
Context: Im from Colombia, a dollar is equivalent to 5000 colombian pesos.  I have a mortgage of 200M pesos.

Problem, when I create a mortgage with value 214'390720 I'm receiving this error

"[Exception] Error: Can't convert to integer: 21439072000" 

Note the additional two 0s at the end

**Comment by crorodriguezro** [comment]
Max acceptable value seems to be 21M

**Comment by j-f1** [comment]
I believe this was fixed by https://github.com/actualbudget/actual/pull/387 which was released with v22.12.9 of Actual. (The new hard limit is 90,071,992,547,409.91)

**Comment by rich-howell** [comment]
Hey @crorodriguezro 

Are you able to confirm that you are on version v22.12.9 of Actual? If your not you could try upgrading and attempting to insert your value again.

Cheers
Rich

**Comment by MatissJanis** [comment]
👋 As Rich and Jed already mentioned: we believe this is solved in v22.12.9.

I'll close this ticket for now, but please feel free to re-open if the issue persists with the latest version.
