### ISSUE TITLE
Not listening on all addresses by default

### ISSUE THREAD

**Issue by heilerich** [actualbudget/actual-server#108]
The hostname in the default configuration is `0.0.0.0` which will only listen on all available IPv4 addresses. This means the default configuration will not work in IPv6 only environments and work only unreliably in dual stack environments (such as many hosting providers).

The hostname in the default configuration should be changed to `::` which will listen on both IP stacks. The notation might suggest that this would make it IPv6 only but this is not the case.

**Comment by j-f1** [comment]
That’s a good idea! Would you be willing to open a PR?
