### ISSUE TITLE
Importing or Creating a New File overwites all the budget files to be the same

### ISSUE THREAD

**Issue by greggotcher** [actualbudget/actual-server#113]
I'm trying out actual budget so I can move away from YNAB.  I created a Test Budget to play with and it was looking good, so I downloaded my YNAB budget and imported it into actual budget.  Then when I went into my Test Budget again it had all of the info that I imported from my YNAB Budget.  I then created a New FIle and when I went into my YNAB Budget and my Test Budget, all of the info was gone and it was showing like a brand new File for all three of the budgets that I have.

I am running this on unRaid and I created a path for data persistance like the instructions say to do.  Any help is greatly appreciated.

**Comment by j-f1** [comment]
We’re aware of this issue and currently tracking it here: https://github.com/actualbudget/actual/issues/511

If you’re able to get HTTPS working for your server, you shouldn’t experience this issue.

**Comment by greggotcher** [comment]
Thanks for the info.  I am now running Actual thru Traefik which is providing HTTPS and it did resolve the issue.
