### ISSUE TITLE
Actual should not require HTTPS for local traffic

### ISSUE THREAD

**Issue by HStep20** [actualbudget/actual-server#124]
It was a nice surprised to get on to add my grocery receipts to my budget and see that I couldn't access my budget locally anymore. 

While I can understand the thought process of "Forced Security" for users, I really dislike the notion of being made to use an HTTPS cert just to access my locally hosted app. I personally do not, and will not, be opening my personal finances up to the world, and want to run everything locally over http for use at home. When Im out, I use a VPN to access my network and use my budget. 

Its a great program, but no other selfhosted things out there I can think of (except maybe Code-Server) require a user to set up a cert for proper local access. I understand my infrastructure, and make choices around that, so Itd be great to not be limited by the application for the choices I do make regarding security.

I did read through the [documentation page](https://actualbudget.github.io/docs/Troubleshooting/SharedArrayBuffer/), but the three provided "solutions" aren't really that tenable. It should be my choice to open a service up to the wild west of the internet, and directing users (who may not understand what theyre doing) to do this, just sounds like it will end terribly. I use Wireguard as a vpn, so why should I change that *just* to be able to use actual at all? 

Perhaps a docker environment variable, allowing the end user to choose the security 'strictness' of access could be a solution for providing that option, while leaving things available to users who don't want to go through the process of setting up a local cert, just to use their budget.

**Comment by j-f1** [comment]
There’s some important context at https://github.com/actualbudget/actual/issues/637 — this is about subtle but serious functionality issues, not about security.

**Comment by j-f1** [comment]
Closing this issue as a duplicate for now
