### ISSUE TITLE
Option to disable sync

### ISSUE THREAD

**Issue by chuckn246** [actualbudget/actual-server#134]
Is there an option to disable the sync feature?

I would prefer to keep the data locally and use my own method of backup.

Edit: I may have misinterpreted the text in the documentation about cloud syncing

**Comment by chuckn246** [comment]
Yeah, I think I misinterpreted the documentation.
Sorry! :)

**Comment by j-f1** [comment]
Let us know if there’s something we can clarify in the documentation so other people don’t misinterpret it!

**Comment by chuckn246** [comment]
It was this section of [this page](https://actualbudget.com/docs/overview/syncing-across-devices/) that threw me off (emphasis mine):
> **That's why we automatically sync all of your data to the cloud in the background.** You get the best of both worlds: all data is local by default, but if internet is available, your data is seamlessly backed up and synced to all other devices. This is the opposite of most apps which heavily rely on the internet to be available.
>
>For the super privacy-focused, it even allows for your data to be [end-to-end encrypted](https://actualbudget.com/docs/overview/syncing-across-devices/) since all our server is doing is passing around changes. **We don't care to read it or sell it to third parties.**
>
>Even if you don't use end-to-end encryption, we will always treat your data as if it's the most sensitive information in the world. It's always stored with bank-level 256-bit AES encryption, and we always transmit it encrypted with SSL/TLS.

Which, now that I'm reading it again, I'm wondering if the data is sent _somewhere_, or is that a relic from before the application went to self-hosted/Open Source?

If it is sent somewhere, I'd like to know where - and why isn't there an option to disable it?

**Comment by j-f1** [comment]
Ah, that website has the docs for the old, hosted-by-James version of the app (we should fix that sometime!). The updated version of that page is at https://actualbudget.github.io/docs/Getting-Started/sync.

**Comment by chuckn246** [comment]
Haha, I think that’s why I originally closed this. I found the link I referenced, opened the issue then found the link you shared and closed it.

I really appreciate you taking the time to respond and clear things up for me!
