### ISSUE TITLE
Actual-server not accessable via nginx location reverse proxy

### ISSUE THREAD

**Issue by anthonymesa** [actualbudget/actual-server#142]
I have Actual-server running behind an nginx reverse proxy. If I set it up so that it serves the URL luridarc.com with root server location (/) with a proxy pass to localhost:5006, I don't have any issue accessing it via luridarc.com, but If I try and change the location being served to /budget, when I visit luridarc.com/budget, it just displays a blank white page because it is trying to load the javascript files from the luridarc.com/ location. 

How can I configure the actual-server to run from the URL luridarc.com/budget so that it looks for its resources at /budget appropriately?

**Comment by j-f1** [comment]
Hi! We’re tracking this feature request in https://github.com/actualbudget/actual/issues/672.
