### ISSUE TITLE
armv6 support

### ISSUE THREAD

**Issue by intiplink** [actualbudget/actual-server#179]
Previously i did some changes personally by changing to alpine images (debian not supporting armv6 anymore), local build, and it works on this cpu. now that this repo have officially added alpine images, please add support to armv6 cpu. 

Tested using RPi zero W and running fine.

edit: on second tought, it seems that bcrypt and sqlite is not build when using github CI, thus its server is "not set up correctly"

**Comment by j-f1** [comment]
If you can get the image build to work on GitHub Actions, please open a PR to add it!

**Comment by j-f1** [comment]
This has been added in #182, thanks for sorting it out and cleaning up the actions @intiplink!
