### ISSUE TITLE
edge tag no longer contains all arches

### ISSUE THREAD

**Issue by Jackenmen** [actualbudget/actual-server#183]
Something changed within the last day because now a single tagged image no longer contains all architectures:

- current edge build only has linux/arm64: https://github.com/actualbudget/actual-server/pkgs/container/actual-server/83903437?tag=edge
    - other tagged images seem to just have a single random architecture (maybe the last one built/pushed?) available:
        - amd64 on sha-6f7306c: https://github.com/actualbudget/actual-server/pkgs/container/actual-server/83847108?tag=sha-6f7306c
        - arm/v7 on sha-6f7306c-alpine: https://github.com/actualbudget/actual-server/pkgs/container/actual-server/83818607?tag=sha-6f7306c-alpine
        - arm/v7 on sha-063d468-alpine: https://github.com/actualbudget/actual-server/pkgs/container/actual-server/83804879?tag=sha-063d468-alpine
        - arm64 on sha-063d468: https://github.com/actualbudget/actual-server/pkgs/container/actual-server/83803609?tag=sha-063d468
- build from 1 day ago just has all architectures (linux/amd64, linux/arm/v7, linux/arm64): https://github.com/actualbudget/actual-server/pkgs/container/actual-server/83637851?tag=sha-7e88de1

**Comment by j-f1** [comment]
We’re discussing this in #182 and hope to have a fix soon.

**Comment by intiplink** [comment]
I'm testing on my fork, using phone. Hope it's working so after got PC I can create PR

**Comment by j-f1** [comment]
No need to rush! We document that the edge image can have problems, and we aren’t planning a release in the immediate future.

**Comment by j-f1** [comment]
I believe this is now fixed.
