### ISSUE TITLE
Remove Express "x-powered-by" header

### ISSUE THREAD

**Issue by dylmye** [actualbudget/actual-server#247]
Express, by default, reports in HTTP response headers that Express is used to serve the app.

While obviously it takes one look at the repo here to see that this software runs on Express, keeping the x-powered-by header on enables bad actors using automated scanning to target actual server instances. Keeping the feature enabled provides no benefits.

It's a one line change to disable the header, I'm happy to contribute the PR :)

Related links:
* https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#x-powered-by
* https://stackoverflow.com/a/13055495

**Comment by MatissJanis** [comment]
Makes sense. I'd be happy to merge a PR for this.
