### ISSUE TITLE
Adapting actual-server to mobile

### ISSUE THREAD

**Issue by EFLql** [actualbudget/actual-server#25]
It looks terrible on mobile, Please get some hands to fix that.

**Comment by fuzzmz** [comment]
I think this can be considered a duplicate of actualbudget/actual#34

**Comment by RichInSQL** [comment]
This is being worked on here - https://github.com/actualbudget/actual/pull/79

**Comment by rich-howell** [comment]
Hey @EFLql 

This is currently being developed in https://github.com/actualbudget/actual/pull/79 so I am going to go ahead and close this issue. 

Cheers
Rich
