### ISSUE TITLE
GoCardless American Express

### ISSUE THREAD

**Issue by aaronbailey88** [actualbudget/actual-server#250]
Hi team
American express seems to have stopped pulling any transactions from 01 August 2023 - I can see transactions in the API call to /nordigen/transactions and it has the correct balance within the data->balances json node, just under the transactions node I only have July transactions. 

I can also see in the request payload that the end date is todays date 2023-08-16 and start date is 2023-07-01 so there should be transactions for august being requested.

Any ideas?

Thanks
Aaron

**Comment by kyrias** [comment]
It's a problem on the GoCardless side and they're aware of it.

**Comment by aaronbailey88** [comment]
> It's a problem on the GoCardless side and they're aware of it.

Ahh amazing, thank you for the speedy reply!

**Comment by kyrias** [comment]
It's now been fixed, and they also finally implemented support for pending transactions.
