### ISSUE TITLE
why is there no compiled .exe of this program?

### ISSUE THREAD

**Issue by barrywilcox** [actualbudget/actual-server#251]
as title says,  why do you have users go through a long loop of installing a bunch of dependencies and using consoles commands. im perfectly capable of doing this but it would make a lot more sense to build and compile a .exe alongside of your server files so that end-users can run it locally without jumping through hoops.

just a suggestion.

**Comment by shall0pass** [comment]
We have an electron build, which is just an EXE.  The only issue with the exe only approach is that you don't get the benefit of the sync server that actual-server provides.  But, if you just want to run the Actual app on your computer with no ability to also use your phone with the same budget, the electron app can do that for you.  The electron build is still being evaluated for any bugs and a release process has yet to be finished for posting the exe's.

https://github.com/actualbudget/actual/actions/runs/5784154309

**Comment by barrywilcox** [comment]
> We have an electron build, which is just an EXE. The only issue with the exe only approach is that you don't get the benefit of the sync server that actual-server provides. But, if you just want to run the Actual app on your computer with no ability to also use your phone with the same budget, the electron app can do that for you. The electron build is still being evaluated for any bugs and a release process has yet to be finished for posting the exe's.
> 
> https://github.com/actualbudget/actual/actions/runs/5784154309


wonderful thank you, would also be suggested to include this info somewhere in the readme here so that users can find it straight away.

that exe is exactly what i was hoping for.
