### ISSUE TITLE
Deposits in expense category create issue with all future budget balances

### ISSUE THREAD

**Issue by phifre** [actualbudget/actual-server#252]
If you make a deposit (eg 100€) in an expense category, all future budget balances show forever an amount of this deposit (eg 100€), event if there are no budget or no transaction in those future months. The reciprocal situation (making a payment in an income category) does not cause this issue.

**Comment by shall0pass** [comment]
This behavior is by design.  You can read more about how Actual implements the envelope budgeting method here: https://actualbudget.org/docs/budgeting/

_hint: There is an override that will allow expenses to carry over month to month_

**Comment by phifre** [comment]
Thanks for you explanation and for the hint, but It is like if the "Rollover overspending" is already set by default for those negative expsenses, and I am not able to disable it.

**Comment by kyrias** [comment]
_Positive_ balances always roll over, negative ones do not by default.

**Comment by MatissJanis** [comment]
👋 Yup, this is by design.

Feel free to open a feature request [here](https://github.com/actualbudget/actual) for the ability to disable this.
