### ISSUE TITLE
[Feature request] Add end date to repeated Schedules

### ISSUE THREAD

**Issue by gravelfreeman** [actualbudget/actual-server#255]
Hello, 

In this screen I searched a long time and figured out it was probably a missing feature.

We can set when the schedule starts but we can't end it by choosing a date.

![image](https://github.com/actualbudget/actual-server/assets/44218371/919de39b-ff81-4c98-aad8-a609304a5f39)

For example; I had to set 23x scheduled entries for all the individual payments for my appliances, which are monthly payments.

It works but it's time consuming and it's bloating the Schedules page.

**Comment by youngcw** [comment]
fyi, Feature requests should be added in the main project https://github.com/actualbudget/actual

**Comment by gravelfreeman** [comment]
Sorry for that, I'll add them over there. Give me 30 minutes! I'm using actual-server on kube so I didn't knew about the other Github.
