### ISSUE TITLE
#Alienvault Administration 

### ISSUE THREAD

**Issue by Thomasdodson1633** [actualbudget/actual-server#256]
### <span aria-hidden="true">✅</span> Deploy Preview for *actualbudget* ready!

|  Name | Link |
|:-:|------------------------|
|<span aria-hidden="true">🔨</span> Latest commit | 603d840923731b4da5525b28b0f9f54791bb7a2b |
|<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/actualbudget/deploys/64c7bd046cb8b50008f3f383 |
|<span aria-hidden="true">😎</span> Deploy Preview | [https://deploy-preview-1428.demo.actualbudget.org/](https://deploy-preview-1428.demo.actualbudget.org/) |
|<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />![QR Code](https://app.netlify.com/qr-code/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJodHRwczovL2RlcGxveS1wcmV2aWV3LTE0MjguZGVtby5hY3R1YWxidWRnZXQub3JnIn0.S3ZNStA6hFPsTPd7JHlJKaFYalC2Es0pJdVhhNQUsmo)<br /><br />_Use your smartphone camera to open QR code link._</details> |
---

_To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/actualbudget/configuration/deploys#deploy-notifications)._

_Originally posted by @netlify[bot] in https://github.com/actualbudget/actual/issues/1428#issuecomment-1657280777_

**Comment by MatissJanis** [comment]
What's this @Thomasdodson1633 ?
