### ISSUE TITLE
Proposal: progress bars and targets

### ISSUE THREAD

**Issue by quasicat0** [actualbudget/actual-server#264]
A recent ActualBudget user and a long time YNAB ~~slave~~ client here.

So far I'm enjoying the app, but I really miss those two features. What do you think abt it?

**Comment by youngcw** [comment]
Take a look here:
https://github.com/actualbudget/actual/issues/1006
https://github.com/actualbudget/actual/issues/496

No one has made an attempt yet, but it would be welcome.

**Comment by MatissJanis** [comment]
Closing as duplicate. Please continue discussing in the issues linked above.
