### ISSUE TITLE
[Bug]: Unable to authenticate with server -> Syncing has been reset on this cloud file.

### ISSUE THREAD

**Issue by PuskyWasTaken** [actualbudget/actual-server#271]
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

I am hosting the Actual-Server app on Google Cloud Run. Randomly, an error occurs with the message "Unable to authenticate with server." on all devices. This error is followed by a subsequent error message stating, "Syncing has been reset on this cloud file." whenever I log out and re log-in on each device. 

This is very problematic as it results in potential data loss and inconvenience due to the need to reset and re-login on each affected device.

It's the same error for both phones and browsers, all devices.

Any ideas on how to get the sync process to function seamlessly across devices without encountering authentication issues?

Additional Information:
* Version being used: Latest at the moment of writing this. v23.10.0
* All settings are default, running using Google Cloud Run from docker image.

### What error did you receive?

![image](https://github.com/actualbudget/actual-server/assets/49597849/97d6660d-7d7b-48ed-ab6e-0782590ffbfa)
![image](https://github.com/actualbudget/actual-server/assets/49597849/c303c26f-8fe3-417d-a2de-72b6a0910c89)

### Where are you hosting Actual?

Docker

### Operating System

Mobile Device

**Comment by youngcw** [comment]
Did you reset your sync id?  If yes, this is expected.

For authentication issues its likely something in your network setup causing trouble. Self signed certs can cause those kinds of issues if that's part of your setup.

**Comment by youngcw** [comment]
Did you reset your sync id?  That would require reverting the file.

**Comment by PuskyWasTaken** [comment]
There's no setup. Just the deploy done on Google Cloud Run, similar to how a deploy on pika pods would work.
All ports open, no network issues. No logs that would indicate this too. No self signed certs.

I have no idea how to reset the sync id. This error is happening periodically even if I don't log anything for a few days. Pod uptime is 100% too. I've checked.

**Comment by PuskyWasTaken** [comment]
Any updates here? Is there anything else I can provide? The issue keeps occuring.

**Comment by janisBerz** [comment]
I have a similar issue. I have a few accounts configured with 'GoCardless' but they have stopped syncing. I get `Unable to authenticate with server` messages and nothing happens. 
![image](https://github.com/actualbudget/actual-server/assets/38721775/80230536-0a6e-40d2-9fda-c27281fbb26a)

When I try to create a new account I cannot link it via `GoCardless` bank sync:
![image](https://github.com/actualbudget/actual-server/assets/38721775/b0310552-cd65-4f30-a692-7b72b6a51865)

**Comment by PuskyWasTaken** [comment]
Still happenes. I have recreated the pod multiple times, I tried different versions, I tried having permanent cpu allocation. Every time it lasts for one day max until the error comes back. 

At this point, sadly, this is unusable for me.  A big shame, because it seemed like such a cool project.

**Comment by PuskyWasTaken** [comment]
Quick question here:
Could it be that actual-server can't handle restarts of any sort?

**Comment by youngcw** [comment]
I restart the server all the time for updates and have no issues.  Is your docker container using persistent storage?  I could see this issue happening if the server storage isn't setup properly.

**Comment by elendil7** [comment]
I get the exact same issue - though the docker compose file seems to be set up fine, with a persistent volume (bind mount: host <=> container).

The message that comes up at the bottom right of the screen is as follows:
![image](https://github.com/actualbudget/actual-server/assets/80429382/24d1fad5-cb13-44be-b641-03b5bd3c19df)

And the status code of the error is as follows:
![image](https://github.com/actualbudget/actual-server/assets/80429382/04571f34-87a6-4474-96e0-960cbaf9857b)

My docker-compose service for actual:
![image](https://github.com/actualbudget/actual-server/assets/80429382/bcd560f1-3c1e-4c9b-bac4-7d736c2a9cce)


Perhaps the following clues shall help remedy this case?
- I use firefox browser - hardened.
- There seems to be no comorbidity or correlation between starting / stopping the docker containers, and the actual server failing to authenticate me.
- As per @PuskyWasTaken's experience, the issue is remedied on re-creation of the Actual account and reuploading of the exported Actual zip file. However, it returns within a day or so of the container being up (unable to authenticate with server).
- I am using Nginx Basic HTTP auth - username & password. However, I performed various acts of debugging to see if this was the culprit, and I don't believe it to be.

Any help would be greatly appreciated :)

**Comment by MatissJanis** [comment]
@elendil7 could it be that the container (for whatever reason) is losing the `/data` folder with `user-files` and `server-files`? That might explain the problem.

**Comment by MatissJanis** [comment]
The other thing you could try: when the "unable to authenticate" warning message comes up - click on top right corder on the server button. Then sign-out of the server and sign back in. If this works: the server persistent storage is working as expected and the problem has to be with the session tokens. As in: them expiring too quickly for some reason.

**Comment by elendil7** [comment]
> @elendil7 could it be that the container (for whatever reason) is losing the `/data` folder with `user-files` and `server-files`? That might explain the problem.

Just now, the same bug occurred after I restarted my containers running on docker compose. However, the data seems to still be present in the folder. Bind mount host<=>container.

![image](https://github.com/actualbudget/actual-server/assets/80429382/ffdea4a0-0a98-4132-b9c2-d3227323497c)

> The other thing you could try: when the "unable to authenticate" warning message comes up - click on top right corder on the server button. Then sign-out of the server and sign back in. If this works: the server persistent storage is working as expected and the problem has to be with the session tokens. As in: them expiring too quickly for some reason.

After logging out, it prompts me to make a new account (enter password twice).
After signing in, I click on the "Personal (local)" budget data to open it.
After clicking on it, the following error message is displayed (bottom right of screen):
![image](https://github.com/actualbudget/actual-server/assets/80429382/36374fae-ecb9-43df-8ce9-9175e54a2417)

This probably means the data has somehow been unlinked from my account. Ceases to exist on the server, but remains on the browser, to be exported but then reimported in a new account.

Another thing to note is that the GoCardless link is also lost, and I have to set it up again each time this bug occurs.

**Comment by MatissJanis** [comment]
We chatted on Discord about the problem. Here: https://discord.com/channels/937901803608096828/940290142579605514/1178395372008263710

Long story short: it was a misconfiguration. The `data` folder (which contains the server database) got deleted and thus the client lost connection and showed the warning message. I am fairly certain the same issue is also happening for @PuskyWasTaken .

So my recommendation is: check the creation and last modification date of the `data` folder. If it's very recent: your system is likely deleting it which is making `actual-server` recreate it in a blank state. In this case the fix will be up to you. To figure out how to make a folder persisted throughout the lifecycle of the deployment.
