### ISSUE TITLE
[Bug]: Where’s the server? Message

### ISSUE THREAD

**Issue by risharde** [actualbudget/actual-server#291]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Actual UI will not detect the server it's on (running in docker and exposed to the internet)
Urgent, please advise, using self signed cert.
![image](https://github.com/actualbudget/actual-server/assets/33866403/85037662-7c2b-41f4-9a4d-2d1e1511b0cf)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by rich-howell** [comment]
Please check this https://github.com/actualbudget/actual-server/issues/266 you might have more luck getting help [here](https://discord.gg/8JfAXSgfRf)

**Comment by MatissJanis** [comment]
Thanks for reaching out. As Rich already mentioned: Discord would be best suited for support requests. Someone in the community is more likely to help out there.

As this is not really a bug report, but most likely a misconfiguration - closing the report.
