### ISSUE TITLE
[Bug]: Importing a local file from a recent version of the app to an older version running on PikaPods doesn't work

### ISSUE THREAD

**Issue by GalaticStryder** [actualbudget/actual-server#319]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

After upgrading my local server to v24.3.0, all went just fine, my budget loaded properly. But after trying to import the zip file on PikaPods, it throws a migrations error and doesn't do anything. I've read the documentation and it says to download sqlite explorer and do some magic using it but I think this could be troublesome. Is there any other way to rollback my version to v24.2.0 again and then export the zip file again? I've tried npm update, yarn cache clean, but the interface still shows v24.3.0 locally.

### Where are you hosting Actual?

None

### Operating System

None

**Comment by youngcw** [comment]
There is no way to undo the migration without messing with the db manually.  The only thing to do for pika pods is to wait until they update (usually about a week behind to confirm stability) or load up an older, pre update version

**Comment by youngcw** [comment]
That would work
