### ISSUE TITLE
[Bug]: sync at top right button does not update accounts via GoCardless

### ISSUE THREAD

**Issue by lucharo** [actualbudget/actual-server#320]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When I click the top right button "Sync" it runs very quickly and doesn't update any of the accounts link via GoCardless. To update them I need to go account by account and sync each of them manually, see video attached:

https://github.com/actualbudget/actual-server/assets/47890755/13d97b31-1a5d-4493-8e07-2ee4395d61a9

### What error did you receive?

No error in CLI or and this is all I'm getting from the browser console:

```
Syncing since 2024-02-28T20:43:01.038Z-0013-b500fe2ef778fb90 0 (attempt: 0)
index.web.ts:5 Got messages from server 0
```

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Other

### Operating System

Mac OSX

**Comment by youngcw** [comment]
You need to use the sync button in the account table, the top one is for syncing your file with the server.
https://actualbudget.org/docs/advanced/bank-sync#frequently-asked-questions

**Comment by lucharo** [comment]
I see @youngcw , thanks for the quick reply, maybe the 2 buttons can be named differently!

**Comment by Kidglove57** [comment]
@lucharo you are not the first one to be confused between those two sync buttons.

You mention syncing each account individually. What works for me is to go to the “All Accounts” view then click  sync (top of register left side!!). This updates all my linked accounts (well only have two that Go Cardless works with …)
