### ISSUE TITLE
[Bug]: Discover Card Transaction Dates are coming in as "New" but are a year old.

### ISSUE THREAD

**Issue by littlehoushontheprairie** [actualbudget/actual-server#323]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When I synced my Discover Card activity from the SimpleFin bridge, the old transactions come up as newer transactions. Exactly a year off. I have verified this via my bank statements.

From Actual Budget:
<img width="1191" alt="Screenshot 2024-03-17 at 08 06 38" src="https://github.com/actualbudget/actual-server/assets/11137891/2042970c-1149-4183-ab4f-b0624d625b8b">

From Discover:
<img width="964" alt="Screenshot 2024-03-17 at 08 03 45" src="https://github.com/actualbudget/actual-server/assets/11137891/f993ff9d-77cc-4d83-ac2a-f800e22be625">

I can manually change this for this instance but I haven't verified my other bank yet.

### What error did you receive?

n/a

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Other

**Comment by littlehoushontheprairie** [comment]
I can verify my other accounts are okay since the bank itself only allows the last 6 months. Discover on the other hand does over a year.

**Comment by MatissJanis** [comment]
👋 Can you check the server logs and provide those?

My bet would be that this is a bug in SimpleFIN. And if they provide us with incorrect dates - there is no way for Actual to fix them on our end.

**Comment by littlehoushontheprairie** [comment]
Sure. 
[639bfa061c2aeb3adcee52ef4a59776cb8b19e8232eaef4448983afb3a42a525-json.log](https://github.com/actualbudget/actual-server/files/14736087/639bfa061c2aeb3adcee52ef4a59776cb8b19e8232eaef4448983afb3a42a525-json.log)

**Comment by MatissJanis** [comment]
Would you mind clicking the "sync" button in the UI and then providing the server log? It should have a JSON of all the transactions there. The current output you sent does not have these transactions.

> Btw is there a way to ignore those transactions?

Sadly - no.

**Comment by MatissJanis** [comment]
Sadly that's still not the output I'm looking for. It should be something like this:

```
{
  top10SortedTransactions: '[{"transactionId":"20220101001","bookingDate":"2022-01-01","valueDate":"2022-01-01","transactionAmount":{"amount":"5.01","currency":"EUR"},"creditorName":"JOHN EXAMPLE","creditorAccount":{"iban":"PL00000000000000000987654321"},"debtorName":"CHRIS EXAMPLE","debtorAccount":{"iban":"PL12345000000000000987654321"},"remittanceInformationUnstructured":"TEST BANK TRANSFER","remittanceInformationUnstructuredArray":["TEST BANK TRANSFER"],"balanceAfterTransaction":{"balanceAmount":{"amount":"448.52","currency":"EUR"},"balanceType":"interimBooked"},"internalTransactionId":"casfib7720c2a02c0331cw2"}]'
}
```

It will be visible in your server logs after clicking the "sync" button in the UI

**Comment by littlehoushontheprairie** [comment]
Yeah. I clicked on the sync button twice for that account. The logging is not spitting that out. Every time I have ran it, it just returns date ranges. 

'''

{"log":"Checking if there are any migrations to run for direction \"up\"...\n","stream":"stdout","time":"2024-03-24T18:26:27.441860889Z"}
{"log":"Migrations: DONE\n","stream":"stdout","time":"2024-03-24T18:26:27.461469003Z"}
{"log":"Listening on :::5006...\n","stream":"stdout","time":"2024-03-24T18:26:27.463869931Z"}
{"log":"2023-12-25 - 2024-04-01\n","stream":"stdout","time":"2024-03-24T18:26:41.57668148Z"}
{"log":"2023-12-31 - 2024-04-01\n","stream":"stdout","time":"2024-03-24T18:43:04.693467623Z"}
{"log":"2023-12-25 - 2024-04-01\n","stream":"stdout","time":"2024-03-24T18:43:13.227078156Z"}
{"log":"2023-12-25 - 2024-04-01\n","stream":"stdout","time":"2024-03-24T18:44:56.931701792Z"}
'''

From docker:
'''

Checking if there are any migrations to run for direction "up"...
Migrations: DONE
Listening on :::5006...
2023-12-25 - 2024-04-01
2023-12-31 - 2024-04-01
2023-12-25 - 2024-04-01
2023-12-25 - 2024-04-01
'''

**Comment by MatissJanis** [comment]
Interesting.. we might not actually have SimpleFin logging then (GoCardless does have it though). Something we should definitely add. But that's a separate issue.

As for your issue: my bet is still on SimpleFin returning incorrect transaction dates. Maybe there is a way to check what's the data that SimpleFin gets in their portal.. I would recommend reaching out to the community on the discord. They are quite active there relating to SF and other issues.

Sadly I won't be able to assist further here as I don't use SimpleFin.

**Comment by littlehoushontheprairie** [comment]
No worries. I kinda realized that once you started to point out how it works. We can close the ticket.
