### ISSUE TITLE
[Bug]: Failed docker compose

### ISSUE THREAD

**Issue by BulldozerPete** [actualbudget/actual-server#326]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Hallo,

I can't setup a docker container with the provided docker compose.yml: https://github.com/actualbudget/actual-server/blob/master/docker-compose.yml

Portainer shows me this error: 
<img width="509" alt="photo" src="https://github.com/actualbudget/actual-server/assets/61943052/aab71a1f-e981-4ff8-bd00-c08b31f71982">
Other containers work fine. What is wrong here?

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by MatissJanis** [comment]
👋 We don't use Github issues for tech support. Please reach out to the community in the community discord. I'm sure someone will help you there.

Closing as this is not a bug report.

**Comment by youngcw** [comment]
If you haven't enabled any of the environment variables it wont work.  Try just enabling the data sync size ones.

**Comment by BulldozerPete** [comment]
I don't understand.

**Comment by letshin** [comment]
Comment out line 9 in the docker compose. `    environment:
`

**Comment by BulldozerPete** [comment]
Done. Container now starts but webpage won't load.
