### ISSUE TITLE
[Bug]: "ultimateCreditor" information from GoCardless is not used

### ISSUE THREAD

**Issue by Nebukadneza** [actualbudget/actual-server#331]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When importing transactions from GoCardless, the information in the Payee/Notes field is often lacking. With my bank, Sparkasse Karlsruhe, "Notes" is never populated at all. The "Payee" is often very unhelpful, since many businesses use a payment provider for their card payments. Then, only the provider or a generic description ends up in "Payee". This seems to be the `creditorName` field. Often, a `ultimateCreditor` field is available in GoCardless data. If this field is available and populated, it should be used instead of the `creditorName`. This way, more sensible information can reach the user.

Example of a `creditorName` i often see is "Lastschriftzahlung" (=debit charge). Not helpful - the `ultimateCreditor` would then include "Some Nice Cafe where i bought a cake".

### Where are you hosting Actual?

Docker

### Operating System

None

**Comment by MatissJanis** [comment]
👋 Yes, the content returned from GoCardless is very inconsistent. This is mostly the different banks fault as they implement as there doesn't seem to be a consistent standard they use.

Feel free to implement your own bank mapper that has the normalization/fields/mapping of the data returned from your bank.

More info here: https://github.com/actualbudget/actual-server/blob/master/src/app-gocardless/README.md

**Comment by Nebukadneza** [comment]
Hi Matiss,

and thanks for the pointer, that looks really good and not too hard. Would this be a local change for me, indefinitely, or would transaction formatting for specific banks something that´s accepted as a PR into upstream here?

**Comment by MatissJanis** [comment]
It would definitely be accepted upstream as long as the change is isolated to your specific bank. 

See here: https://github.com/actualbudget/actual-server/blob/master/src/app-gocardless/README.md

There's already quite a few bank intergations available there that you can use as an example.
