### ISSUE TITLE
[Bug]: Windows app won't connect, browser works.

### ISSUE THREAD

**Issue by Radiobiscuit** [actualbudget/actual-server#393]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Not necessarily a bug, but I'm having difficulty getting the Windows app to connect to a local server.

I'm running actual-server on my local network and I have self-certified for HTTPS and can connect and use the server using the web interface (with the usual warnings from the browser about self certification). However, when I try the Windows app, it refuses to connect saying that either the server is down or that HTTPS is incorrectly configured.

Sadly I don't know much about configuring HTTPS and would be very grateful if someone could point me in the right direction?

I'm running Ubuntu 24.04 LTS for the server and Windows 10 for the browser/app. The app is 24.07.0

### What error did you receive?

Server is not running at this URL. Make sure you have HTTPS set up properly.

URL is https://10.1.1.216:5006

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

**Comment by MatissJanis** [comment]
Hi,

Please visit our [community discord](https://discord.gg/pRYNYr4W5A) for tech support. I'm sure folks there will be able to assist!
