### ISSUE TITLE
Using localhost:5006 is not working

### ISSUE THREAD

**Issue by sobrinho** [actualbudget/actual-server#40]
<img width="1840" alt="Screen Shot 2022-05-20 at 15 42 55" src="https://user-images.githubusercontent.com/26460/169592508-ffe66afd-ad85-4de9-9a87-00eb89b901f7.png">
<img width="1840" alt="Screen Shot 2022-05-20 at 15 43 00" src="https://user-images.githubusercontent.com/26460/169592524-d47dbd28-ea90-47a2-8bc9-1e1cce7ae62e.png">

**Comment by sobrinho** [comment]
Same issue running though docker.

**Comment by PartyLich** [comment]
There might be more relevant info about your setup, but based on the screenshot you've included [this section of the readme](https://github.com/actualbudget/actual-server#configuring-the-server-url) seems important
> Since Actual doesn't know what server to use, the first thing it does is asks you for the server URL. If you are running this project, **simply click "Use this domain" and it will automatically fill it in with the current domain. This works because we are serving the app and server in the same place.**

**Comment by gradiuscypher** [comment]
@PartyLich - I've just tried to spin up a server and have been met with the same issue and same log lines that were in the first screenshot. I've tried using a few variations of the URL including `http://localhost:5006` as well as the server's IP address. 

If I use localhost as previously mentioned, that page reports back with an "unable to find server". But if I use the server's IP address (which is what is filled out when clicking "Use this domain"), the OK button just turns into a forever spinning loading button and never progresses. There's no notable errors in either the browser console or the server's logs other than what's already been shared. Happy to provide any additional information that might help with debugging.

**Comment by gradiuscypher** [comment]
As a quick follow up, I spun up a Docker container on my localhost to see if I could replicate this same bug (previously was hosting on a kubernetes cluster). Experienced the same behavior as before. I've included the full logs from the start of the container up to and including the request that seems to be stalling or erroring.

https://gist.github.com/gradiuscypher/33962aeada25261781b8eb11a21ae953

**Comment by PartyLich** [comment]
I'll have another look and see if I can garner some insight as soon as time allows. At the moment I can't reproduce the problem.

**Comment by gradiuscypher** [comment]
Not a problem, I'll see if I can take a look at the code sometime in the next few days and potentially narrow down what might be going on. I'm less experienced with JS, so I'm not overly confident in my abilities, but I'm willing to give it a shot :)

**Comment by JazzaG** [comment]
This is caused by the change to `util/error-middleware.js` in [this commit](https://github.com/actualbudget/actual-server/commit/592f0540f940d260033b95340c34a9b8b8072aed)

See https://expressjs.com/en/api.html

>Error-handling middleware always takes four arguments. You must provide four arguments to identify it as an error-handling middleware function. Even if you don’t need to use the next object, you must specify it to maintain the signature. Otherwise, the next object will be interpreted as regular middleware and will fail to handle errors.
