### ISSUE TITLE
Applying prettier

### ISSUE THREAD

**Issue by PartyLich** [actualbudget/actual-server#42]
The repo contains a prettier config and relevant infrastructure, but actually running prettier (eg `npx prettier -c .`) produces a decent sized list of discrepancies.

Is there a desire to fix prettier's list of complaints? Purely style changes are super noisy imo, so I'm not making any assumptions about the plan.

We've also added `eslint-plugin-prettier`, but the prettier rule isn't enabled (and thus eslint doesn't actually produce notices for any prettier specific problems).

**Comment by TomAFrench** [comment]
Thanks, I missed that in my PR. Just made a new one to enforce the prettier rules.

I'm strongly in favour of being as strict as we can about code style if we can automate it, otherwise open source projects end up with a hodge-podge of 5 different code styles.

(Plus I think it would be a bit ironic if we didn't enforce prettier properly here.)

**Comment by TomAFrench** [comment]
Our `.prettierrc.json` is pretty sparse though so it might be worth fleshing this out in future.

**Comment by PartyLich** [comment]
The suggested rules (unless I've misunderstood one of them; I don't actually use prettier in my projects; everything I'm aware of that it could do to source can be handled by eslint, so it feels redundant to me) look reasonable to me.

Hopefully not muddling things, but it feels related to me: While we're adjusting style/lint rules, could we also consider:
```js
    '@typescript-eslint/no-unused-vars': [
      'warn',
      {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_'
      }
    ]
```
Makes it possible to distinguish intentionally unused vars (`_next`) that may nonetheless be necessary as in #46.

**Comment by MatissJanis** [comment]
👋 Looks like the lack of prettier has already been addressed. I'll close off this issue.
