### ISSUE TITLE
Irreparable "Your data is out of sync" when using account on multiple devices.

### ISSUE THREAD

**Issue by jokeofweek** [actualbudget/actual-server#44]
👋 Not sure if this is a dupe of https://github.com/actualbudget/actual-server/issues/23, so filing separately just in case.

# Setup
I'm currently running Actual on a GCP instance, using [this Dockerfile](https://github.com/actualbudget/actual-server/blob/master/Dockerfile) as part of a larger docker-compose, at this hash: 44d045f546ceb2440f2a681bc5821bbb8eefb80f. Nothing seems to have been merged into master since then that would impact this.

# Steps to reproduce

1. Open web UI on two distinct devices, downloading the same account.
2. On device A, add a new transaction.

# Problematic behavior

On device B, you'll get this error on next sync (or load) even. Note that you don't need to add or change anything on B.

![a](https://user-images.githubusercontent.com/429825/169625375-c2dc8694-32f6-46d3-97a9-4d113d360fc7.PNG)

If you press repair:

![b](https://user-images.githubusercontent.com/429825/169625388-7b4543b9-4b6b-4954-95be-16e31f596e13.PNG)

# Expected behavior

I expected to be able to sync and work on an account across multiple devices, given the CRDT logic.

**Comment by orangetechllc** [comment]
I experienced this same issue.

**Comment by bjornbostrom** [comment]
Also getting the same result as of hash [3fee9cb](https://github.com/actualbudget/actual-server/commit/3fee9cbb4260d064328938c4f0da062695f3b0d2)

**Comment by bjornbostrom** [comment]
Pull request #52 (currently not yet merged to master) seems to fix this 👍

**Comment by kinwolfqc** [comment]
Any ETA on that PR?  I have to work away from my main computer every second week and I can't do the budget while away because of the bug(scared of losing data, so I prefer not to chance it)  Thanks!

**Comment by distefam** [comment]
Any update on this?

**Comment by kinwolfqc** [comment]
PR is in, and I deployed it, but I still have the problem.  I opened my budget on the second computer, and I got the yellow warning, then the red one (Your data is still out of sync)  Not sure how to debug this, or supply more informations, logs, but I'd love to them if someone tells me where they are.

**Comment by Teprifer** [comment]
> PR is in, and I deployed it, but I still have the problem. I opened my budget on the second computer, and I got the yellow warning, then the red one (Your data is still out of sync) Not sure how to debug this, or supply more informations, logs, but I'd love to them if someone tells me where they are.

@kinwolfqc This worked for me: Open settings and export your data, 'close file' and delete your budget, (may need to 'close file here when it creates another default budget for you), and then re-import what you just exported.

**Comment by rich-howell** [comment]
This is potentially going to be resolved with https://github.com/actualbudget/actual-server/pull/75

**Comment by rich-howell** [comment]
Hey @jokeofweek 

We have merged a fix into master that fixes this issue, give it a go and if the issue persists give me a shout and I will re-open this issue.

Thanks for raising this

Cheers
Rich
