### ISSUE TITLE
[Bug]: Budget note field doesn't vanish on touch devices

### ISSUE THREAD

**Issue by arnholdsan** [actualbudget/actual-server#443]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When I was finished entering a note on the budget screen (within a category), I tapped somewhere else because that's how I close the note field when I work with a trackpad. The bug is that with touch input (finger) the note stayed there and didn't vanish.

When I later used my trackpad, it worked as it should. When I proceed with touch, the note field stays there again. It has to do with touch input/latency(?) I think.

### What error did you receive?

Didn't receive an error, the note field just stayed and was sort of "freezed".
![Screenshot 2024-09-01 204846](https://github.com/user-attachments/assets/3ea0371b-df56-4fd2-8646-45ec6132f964)

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by MikesGlitch** [comment]
Should be fixed here: https://github.com/actualbudget/actual/pull/3342

Demo env: https://deploy-preview-3342.demo.actualbudget.org/
