### ISSUE TITLE
[Bug]: Sync accounts using Gocardless

### ISSUE THREAD

**Issue by pittbull** [actualbudget/actual-server#456]
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

Spinning wheel when connecting to bank (Link Your Bank).

Following this process:

1. Selecting "Add account"
2. Selecting "Norway" then my bank (DNB)
3. Getting forwarded to gocardless for approval and user id
4. Then getting forwarded to my bank for authorization
5. Spinning wheel after successful authentication
7. Spinning wheel in Actual

I can successfully add accounts and see my transactions at Gocardless website.

### What error did you receive?

None - it just sits there.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Safari

### Operating System

Linux

**Comment by MatissJanis** [comment]
👋 Please reach out to the community for tech-support on back-sync via Discord. They are quite active and eager to help: https://discord.gg/pRYNYr4W5A
