### ISSUE TITLE
[Bug]: Cannot find Actual server on Docker

### ISSUE THREAD

**Issue by gerivives** [actualbudget/actual-server#461]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Hello,

I have attempted to install Actual by using Docker without success. The installation and configuration of the server goes successfully. The server is set to use HTTPS on local port 443 mapped to 5006 on the Docker container, with a valid certificate for a FQDN.

When logging in to https://my.fqdn.com, no server is selected by default an I am prompted to specify the location of the server. I have tried the following:
- https://my.fqdn.com
- https://<docker_internal_ip>:5006

Some additional context:
- The Docker container is running in a server on a DMZ network.
- From my PC, I have connectivity to the server on port 443.

Neither of these has worked since an error is raised stating that no Actual Server could be found at that address. What am I missing? The docker container is running properly and no errors appear.

Thanks in advance,

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
👋 Please reach out to the community of Discord for tech support: https://discord.gg/8JfAXSgfRf
