### ISSUE TITLE
[Bug]: Stuck with linking account at "Success! Click to continue"

### ISSUE THREAD

**Issue by treeman** [actualbudget/actual-server#464]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When linking accounts the authentication with GoCardless works well but I get stuck at the "Success! Click to continue" button.

When I try to click it, nothing happens and nothing appears in the console.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Linux

**Comment by matt-fidd** [comment]
I believe this has been fixed with https://github.com/actualbudget/actual/pull/3515

**Comment by treeman** [comment]
Yes, confirmed that it's working. Thank you!
