### ISSUE TITLE
[Server Feature Request]: CI builds

### ISSUE THREAD

**Issue by torculus** [actualbudget/actual-server#467]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

GitHub allows for Continuous Integration builds through GitHub actions, which are free

Since most users (mainly on Windows) don't want to install `npm`, `yarn`, `python`, `Visual Studio Code`, etc. just to build the server, maybe we could consider setting up CI builds for various systems (e.g. Windows, macOS. Linux)?

### Where are you hosting Actual?

Locally via Yarn

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
👋 Hi! Would you mind clarifying what you mean by "ci builds"? What exactly are you looking for here?

The server itself doesn't have any "builds". It's just server-side code you deploy to a server or run locally. If you're looking to use Actual by just downloading a program and running it then look here: https://actualbudget.org/download/

For folks not wanting to install yarn/node - there's always the docker option available.

**Comment by torculus** [comment]
Right, but all of the Docker images are only for Linux. I'm on Windows and would prefer to self-host without installing node, yarn, etc.

**Comment by MatissJanis** [comment]
They should be runable on Windows too. Many people on Win use them. Did you try? If so - what problem are you experiencing with running them on Win?

**Comment by torculus** [comment]
Okay, it was my failure to understand how Actual is structured. I thought you could compile a standalone executable with `yarn`, and I was having trouble doing that. So I figured having a central place to build executables for Windows, macOS, Linux, etc. would be helpful

I'm trying it on Docker now, but still getting issues. I'll just close this issue and open a new one to track that 👍
