### ISSUE TITLE
[Bug]: Nobody can choose "feature request" for `actual-server` on GitHub

### ISSUE THREAD

**Issue by torculus** [actualbudget/actual-server#468]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The "feature request" template doesn't contain any non-markdown fields, and so if a user wants a feature request in `actual-server` (NOT `actual`), they have to choose "bug". Then you have to go in an remove "bug" and add "feature request"

![image](https://github.com/user-attachments/assets/c2600299-23ae-499b-9296-4fcd2e644d54)

### Where are you hosting Actual?

None

### Operating System

None

**Comment by MatissJanis** [comment]
👋 Hi! We post all feature requests to the `actual` repository. Even if those are feature requests for `actual-server`.

Why? Because there's a lot more people viewing and voting on the feature requests there. A single place with everything.

**Comment by torculus** [comment]
Sounds good. Maybe we could just remove the "Feature Request" template from this repo so that others won't get confused? It's dead code anyway
