### ISSUE TITLE
[Bug]: No way of knowing when rate limit will be lifted

### ISSUE THREAD

**Issue by fira42073** [actualbudget/actual-server#488]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

There is no way of knowing when the rate limit is gonna be lifted again when using gocardless

![image](https://github.com/user-attachments/assets/62c88732-1632-4c4c-a5f9-8ab1349d7dd8)

Should be a relatively easy fix to add the actual error from gocardless here
https://github.com/actualbudget/actual-server/blob/603f970f12480c4d871d1a40d277213511e429ac/src/app-gocardless/app-gocardless.js#L226

They claim to return it in their API spec
https://developer.gocardless.com/bank-account-data/endpoints

```json
{
  "summary": "Rate limit exceeded",
  "detail": "The rate limit for this resource is <times>/<time_period>. Please try again in <time_left> seconds",
  "status_code": 429
}
```

Logs do not report anything useful with `DEBUG="*"`
![image](https://github.com/user-attachments/assets/4cc700cc-15da-4c13-a0b8-74676cfeaa73)

### Where are you hosting Actual?

Other

### Operating System

Linux

**Comment by mbrijun** [comment]
I was thinking about the same problem. It could be that there are two rate limits to consider - one imposed by GoCardless, and the other one imposed by the bank. I suspect we could be hitting the latter (the bank rate limit), and not the former.

**Comment by fira42073** [comment]
It may be a good idea to start logging it for now and dealing with the UI
later
Best regards,
Zemfira
