### ISSUE TITLE
[Bug]: Rename without characters is possible on mobile

### ISSUE THREAD

**Issue by OskyEdz** [actualbudget/actual-server#491]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I made the mistake of removing the name of an account in mobile view.
After that it was impossible to change the name again using either mobile or desktop GUI.

It should either be that an account need at least 1 character and re-force the user or
handle unnamed accounts on desktop like on mobile.

### What error did you receive?

Currently you are able to view the account (with no name) on mobile but not on desktop (forced back to all accounts instead)

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Other

### Operating System

Mobile Device

**Comment by matt-fidd** [comment]
Could you reopen this in the [main repo](https://github.com/actualbudget/actual) please?

**Comment by youngcw** [comment]
I think this was fixed already.  Edge doesn't let you set a name to blank

**Comment by matt-fidd** [comment]
Even better!
