### ISSUE TITLE
[Bug]: “Switch budget file” Not Displaying Available Budget Files on Mobile

### ISSUE THREAD

**Issue by ramielsawy** [actualbudget/actual-server#496]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

# Summary

On the mobile version, when selecting “Switch budget file” after opening a budget, a “No budget files” message appears instead of displaying a list of available budgets. This makes it difficult to switch to other budgets directly on mobile. Replacing “Switch budget file” with a “Close file” option, like on the desktop version, would allow users to close the current budget and return to the main budget list. This would simplify accessing and downloading other budgets on mobile without needing to switch to the desktop version as a workaround.

# Steps to Reproduce

1. Using the mobile app, open an account with multiple budgets.
1. Download and open a specific budget.
1. Tap the logo icon and choose “Switch budget file.”

# Expected Behavior

“Switch budget file” should show a list of available budgets so that I can select and download another budget file directly on mobile.

# Actual Behavior

Selecting “Switch budget file” results in a “No budget files” message, even though multiple budgets exist.

# Workaround

Currently, to access a different budget on mobile, I:

1. Open the desktop version.
2. Select the budget name and choose “Close file” to return to the budget list.
3. Download and open the desired budget on mobile.

This workaround is necessary each time I need to access a new, non-downloaded budget file.

# Suggested Solution

Replace the “Switch budget file” button with a “Close file” option, as seen on the desktop version. This would allow users to close the current budget and return to the budget list to select another file.

# Environment

Host: PikaPods
Platform: Samsung - Chrome
App Version: 24.11.0

### What error did you receive?

Selecting “Switch budget file” results in a “No budget files” message, even though multiple budgets exist.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by MatissJanis** [comment]
👋 actual-server is not the correct spot for feature requests/bug reports on the UI.

Please read here: https://github.com/actualbudget/actual-server/issues/266
