### ISSUE TITLE
[Bug]: v24.12.0 SqliteError: no such column: password

### ISSUE THREAD

**Issue by tgiesinger** [actualbudget/actual-server#521]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

After updating to 24.12.0 when the migrations run the following error is thrown (running in unraid on docker)

```
/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9
        this[cppdb].exec(sql);
                    ^
SqliteError: no such column: password
    at Database.exec (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
    at WrappedDatabase.exec (file:///app/src/db.js:30:20)
    at Migration.up (file:///app/migrations/1718889148000-openid.js:4:24)
    at next (/app/node_modules/migrate/lib/migrate.js:35:45)
    at /app/node_modules/migrate/lib/migrate.js:71:9
    at /app/node_modules/migrate/lib/set.js:84:5
    at FSReqCallback.oncomplete (node:fs:192:23) {
  code: 'SQLITE_ERROR'
}

Node.js v18.20.5

/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9
        this[cppdb].exec(sql);
                    ^
SqliteError: no such column: password
    at Database.exec (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
    at WrappedDatabase.exec (file:///app/src/db.js:30:20)
    at Migration.up (file:///app/migrations/1718889148000-openid.js:4:24)
    at next (/app/node_modules/migrate/lib/migrate.js:35:45)
    at migrate (/app/node_modules/migrate/lib/migrate.js:76:3)
    at MigrationSet.migrate (/app/node_modules/migrate/lib/set.js:123:3)
    at MigrationSet.up (/app/node_modules/migrate/lib/set.js:107:8)
    at file:///app/src/migrations.js:23:23
    at /app/node_modules/migrate/index.js:62:5
    at /app/node_modules/migrate/lib/load-migrations.js:97:7 {
  code: 'SQLITE_ERROR'
}

Node.js v18.20.5
Checking if there are any migrations to run for direction "up"...
Checking if there are any migrations to run for direction "up"...
```

### What error did you receive?

```
/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9
        this[cppdb].exec(sql);
                    ^
SqliteError: no such column: password
    at Database.exec (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
    at WrappedDatabase.exec (file:///app/src/db.js:30:20)
    at Migration.up (file:///app/migrations/1718889148000-openid.js:4:24)
    at next (/app/node_modules/migrate/lib/migrate.js:35:45)
    at /app/node_modules/migrate/lib/migrate.js:71:9
    at /app/node_modules/migrate/lib/set.js:84:5
    at FSReqCallback.oncomplete (node:fs:192:23) {
  code: 'SQLITE_ERROR'
}

Node.js v18.20.5

/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9
        this[cppdb].exec(sql);
                    ^
SqliteError: no such column: password
    at Database.exec (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
    at WrappedDatabase.exec (file:///app/src/db.js:30:20)
    at Migration.up (file:///app/migrations/1718889148000-openid.js:4:24)
    at next (/app/node_modules/migrate/lib/migrate.js:35:45)
    at migrate (/app/node_modules/migrate/lib/migrate.js:76:3)
    at MigrationSet.migrate (/app/node_modules/migrate/lib/set.js:123:3)
    at MigrationSet.up (/app/node_modules/migrate/lib/set.js:107:8)
    at file:///app/src/migrations.js:23:23
    at /app/node_modules/migrate/index.js:62:5
    at /app/node_modules/migrate/lib/load-migrations.js:97:7 {
  code: 'SQLITE_ERROR'
}

Node.js v18.20.5
Checking if there are any migrations to run for direction "up"...
Checking if there are any migrations to run for direction "up"...
```

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Other

### Operating System

Other

**Comment by tgiesinger** [comment]
Nevermind, not sure what happened but I restored a pre 24.12.0 version of my sqlite file and the migrtaions ran fine this time. Looks like somehhow my setup got into a state where the sqlite file had already had the migration run on it so of course password didn't exist anymore.

**Comment by MatissJanis** [comment]
👋 You're not persisting the `.migrate` file thus the migrations are getting re-ran each time the container boots.

Solution: https://discord.com/channels/937901803608096828/1310791130492702740/1314715984145158146

**Comment by cipriani14** [comment]
@MatissJanis 

I'm also having this same error using the Unraid app (Unraid 6.12.14). For some reason, Discord link won't take me to the channel/message. It's just opening my Discord DM's. 

I don't have a backup -- that was on my list of things to get setup this week.

**Comment by Quiwy** [comment]
@MatissJanis: Could it make sense to store the [`.migrate`](https://github.com/actualbudget/actual-server/blob/master/src/migrations.js#L13) file in the `serverFiles` folder?

That way, backing up the `serverFiles` folder on server side should be enough to start run without issues with migrations.

**Comment by MatissJanis** [comment]
Uniraid template fix is here: https://discord.com/channels/937901803608096828/1310791130492702740/1315923729993437185

And here's the TLDR for the solution from Discord

<img width="679" alt="Screenshot 2024-12-11 at 19 54 57" src="https://github.com/user-attachments/assets/29605326-f1b3-47fe-a9dd-6415eaf01cf5" />

`.migrate` file:
```
{
  "lastRun": "1719409568000-multiuser.js",
  "migrations": [
    {
      "title": "1694360000000-create-folders.js",
      "timestamp": 1732620313175
    },
    {
      "title": "1694360479680-create-account-db.js",
      "timestamp": 1732620313196
    },
    {
      "title": "1694362247011-create-secret-table.js",
      "timestamp": 1732620313209
    },
    {
      "title": "1702667624000-rename-nordigen-secrets.js",
      "timestamp": 1732620313209
    },
    {
      "title": "1718889148000-openid.js",
      "timestamp": 1732620537307
    },
    {
      "title": "1719409568000-multiuser.js",
      "timestamp": 1732620537315
    }
  ]
}
```

---

This all boils down to `.migrate` file not being persisted. Up until recently the migrations that were running were always backwards compatible, so re-running them again and again didn't cause issues. But recently we introduced a migration that can only be ran once. Which is fine - migrations are expected to be ran once.

But because the `.migrate` file is not persisted in some machines... things blow up.

**Comment by Kjeldgaard** [comment]
@MatissJanis 
I'm not sure I fully understand how to fix this. I'm using AB on Unraid, and my folder structure is as follows:
```
/mnt/user/appdata/actual-server/
├── server-files
│   ├── account.sqlite
│   └── account.sqlite-journal
└── user-files
    ├── file-a2c77b8e-0fc1-4c86-b42f-88bcad5a3893.blob
    └── group-72c0e6a3-6a00-41f9-8215-107d9a474f2b.sqlite
```
From https://github.com/hofq/docker-templates/pull/30 I can see, that new AB templates only have a single folder. I've edited my AB template according to https://github.com/hofq/docker-templates/pull/30. But AB still fails to start. So I think I have to add a `.migrate` file?

Am I suppose to create a `.migrate` file in `/mnt/user/appdata/actual-server/` with the content from https://github.com/actualbudget/actual-server/issues/521#issuecomment-2536985283?

**Comment by imalobster** [comment]
hi @Kjeldgaard, I provided some detailed steps [here](https://github.com/hofq/docker-templates/issues/29#issuecomment-2579948049). Hopefully they will give you enough detail to get unblocked

**Comment by Kjeldgaard** [comment]
> hi @Kjeldgaard, I provided some detailed steps [here](https://github.com/hofq/docker-templates/issues/29#issuecomment-2579948049). Hopefully they will give you enough detail to get unblocked

Thanks a lot @imalobster, you guide helped me getting AB up and running again. Long story short, it was the .migrate file I was missing.

**Comment by jsmith8954** [comment]
Howdy, I'm facing this same issue on a new install of an actual budget instance. (installed with docker using the latest tag)
If I follow the steps to fix, (which I believe is actually skipping the migrations) - the server does start, but has issues because it's not configured.

how do I fix this for a new install, when I can't skip the migrations? 

Thanks!

```
Checking if there are any migrations to run for direction "up"...
/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9
	this[cppdb].exec(sql);
	            ^
SqliteError: database is locked
    at Database.exec (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
    at WrappedDatabase.exec (file:///app/src/db.js:30:20)
    at Migration.up (file:///app/migrations/1694360479680-create-account-db.js:4:24)
    at next (/app/node_modules/migrate/lib/migrate.js:35:45)
    at /app/node_modules/migrate/lib/migrate.js:71:9
    at /app/node_modules/migrate/lib/set.js:84:5
    at FSReqCallback.oncomplete (node:fs:192:23) {
  code: 'SQLITE_BUSY'
}
Node.js v18.20.5
```
