### ISSUE TITLE
Github Container Registry URL 404

### ISSUE THREAD

**Issue by elaske** [actualbudget/actual-server#61]
The available ghcr.io/actualbudget/actual-server url doesn't seem to be working as it 404s for `docker pull`. The  jlongster/actual-server reference does, at least.

**Comment by rich-howell** [comment]
Hey,

I think this is fixed now, if your still having issues let me know and I will re-open this issue.

Cheers
Rich

**Comment by paulhovey** [comment]
Hi Rich, I just tried pulling and am getting this output:

`# docker pull ghcr.io/actualbudget/actual-server
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/actualbudget/actual-server/manifests/latest": unauthorized`
