### ISSUE TITLE
How to connect from mobile app

### ISSUE THREAD

**Issue by UmutAlihan** [actualbudget/actual-server#68]
I downloaded the mobile Actual App from Play Store. It seems to connecting directly to Actual Cloud Servers. How can I change it, so that it points to my selfhosted server instance?

**Comment by RichInSQL** [comment]
Hey, 

It isn't possible at the moment, the mobile apps are not being developed, instead the focus is on a responsive version of the application which is being worked on here https://github.com/actualbudget/actual/pull/79
