### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by notflip** [actualbudget/actual-server#77]
I forgot my password, I logged into the server using `docker exec -ti actual-server sh`, but I can't seem to find the location where the password is stored. Can anyone advice? Thanks!

**Comment by rich-howell** [comment]
Hey @notflip,

Take a look at these files

https://github.com/actualbudget/actual-server/blob/master/util/validate-user.js
https://github.com/actualbudget/actual-server/blob/master/sql/account.sql

That should give you some idea of where to look 

Cheers
Rich

**Comment by notflip** [comment]
Thanks @rich-howell I looked at the docker setup but I'm not sure as to where I can get to the actual data. Should I look for an sqlite file inside the docker container and open that to change the password? Thank you

**Comment by rich-howell** [comment]
There should be a SQL Lite database on your local machine which you can edit, it is stored in the browser storage. If you inspect actual web you should be able to see it (I am not on a computer with actual at the moment so can't screen shot)

**Comment by notflip** [comment]
@rich-howell Great, I managed to open accout.sqlite, I see a hashed password there, what type of hash is used? Then I can set a new one!

**Comment by rich-howell** [comment]
@notflip make a backup of it first and I *think* if you delete it you should be prompted to create a new one when you load actual....

**Comment by notflip** [comment]
It worked! Thank you very much @rich-howell

**Comment by jlongster** [comment]
fwiw the password uses bycrypt: https://github.com/actualbudget/actual-server/blob/master/app-account.js#L16
