### ISSUE TITLE
cant do yarn start....

### ISSUE THREAD

**Issue by gbdavidx** [actualbudget/actual-server#8]
fixed it, but now im getting en error..

debian 11...

<img width="771" alt="Screen Shot 2022-04-29 at 9 45 06 PM" src="https://user-images.githubusercontent.com/26369204/166091410-d0e47270-04ee-44ec-a5d5-4c370fb65277.png">
.

yarn version:
1.22.18

**Comment by wmertens** [comment]
your Node is too old, fs/promises was added in v14 or so. Update to v16 at least, maybe v18 is ok too but better-sqlite doesn't have a build yet.

**Comment by Teprifer** [comment]
Found this issue and used wmertens' response to find this page to resolve it: https://phoenixnap.com/kb/update-node-js-version

**Comment by Niraj-Fonseka** [comment]
Had the same issue. Node 14 worked for me to get around that issue and better-sqlite issue
