### ISSUE TITLE
Missing Blob File

### ISSUE THREAD

**Issue by The-Inamati** [actualbudget/actual-server#90]
Hello,

For some reason I can no longer open my budget. The budget is there but when I click to open it I get the browser error below: 

![image](https://user-images.githubusercontent.com/45592340/203636454-8f184c54-255f-4bb8-bbec-1eb5d0cea503.png)

In the logs I get the error:
```
Error: file does not exist: /app/user-files/file-3a04f6bc-7621-4447-b13b-5ca41aae93b6.blob
```

When I list that directory effectively the file does not exist. What does exist is a directory with the same id.

Ran a git pull but was already on latest. Deleted the container and the image and built it again unsuccessfully. 

Can somebody help? I'm actually surprised how dependant I am on this app.

**Comment by avanheuvelen** [comment]
I'm having the same problem. The file does not exist, but there is a folder with the same UUID.

**Comment by MatissJanis** [comment]
Did you perform [the database migration](https://actualbudget.github.io/docs/Getting-Started/migration/simple-sync) when doing the upgrade to v22.10.25?

**Comment by avanheuvelen** [comment]
@The-Inamati 

I got it to work by checking out and running 32bf923. Export it from there and import it in the master version.

**Comment by The-Inamati** [comment]
@avanheuvelen 

Thank you for your help. I got it to work by doing what you suggested.
