### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by mark-monteiro** [actualbudget/actual-server#98]
I would like to update to 22.12.9 but I haven't been able to find any release notes for this version. Could someone point me to where the release notes are? If there are none, they should be added so that people know what to expect when they update.

**Comment by Kidglove57** [comment]
Here you go:
https://actualbudget.github.io/docs/Release-Notes/

**Comment by mark-monteiro** [comment]
Thanks! Guess I didn't look hard enough, thanks for taking the time to point me in the right direction

**Comment by Kidglove57** [comment]
No worries - personally I think the documentation can be rather hide to find!
